-- Employee Call Monitor - PostgreSQL / Neon schema
-- Run once in the Neon SQL Editor.

CREATE TABLE IF NOT EXISTS managers (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 email VARCHAR(190) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 full_name VARCHAR(160) NOT NULL,
 role VARCHAR(20) NOT NULL DEFAULT 'MANAGER' CHECK (role IN ('ADMIN','MANAGER')),
 active SMALLINT NOT NULL DEFAULT 1 CHECK (active IN (0,1)),
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS employees (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name VARCHAR(160) NOT NULL,
 department VARCHAR(120) DEFAULT NULL,
 active SMALLINT NOT NULL DEFAULT 1 CHECK (active IN (0,1)),
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS devices (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 employee_id BIGINT NOT NULL,
 device_id VARCHAR(190) NOT NULL UNIQUE,
 model VARCHAR(190) DEFAULT NULL,
 battery_level INT DEFAULT NULL CHECK (battery_level IS NULL OR battery_level BETWEEN 0 AND 100),
 last_seen TIMESTAMP DEFAULT NULL,
 call_state VARCHAR(20) NOT NULL DEFAULT 'OFFLINE' CHECK (call_state IN ('READY','IN_CALL','IDLE','OFFLINE')),
 call_started_at TIMESTAMP DEFAULT NULL,
 state_changed_at TIMESTAMP DEFAULT NULL,
 active SMALLINT NOT NULL DEFAULT 1 CHECK (active IN (0,1)),
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_devices_employee FOREIGN KEY(employee_id) REFERENCES employees(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_devices_employee ON devices(employee_id);
CREATE INDEX IF NOT EXISTS idx_devices_seen ON devices(last_seen);

CREATE TABLE IF NOT EXISTS join_tokens (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 token VARCHAR(128) NOT NULL UNIQUE,
 expires_at TIMESTAMP NOT NULL,
 created_by BIGINT DEFAULT NULL,
 used_at TIMESTAMP DEFAULT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_join_tokens_manager FOREIGN KEY(created_by) REFERENCES managers(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_join_tokens_expires ON join_tokens(expires_at);

CREATE TABLE IF NOT EXISTS call_history (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 employee_id BIGINT NOT NULL,
 device_id VARCHAR(190) NOT NULL,
 android_call_log_id BIGINT DEFAULT NULL,
 direction VARCHAR(20) NOT NULL DEFAULT 'UNKNOWN' CHECK (direction IN ('INCOMING','OUTGOING','UNKNOWN')),
 contact_number VARCHAR(80) DEFAULT NULL,
 result VARCHAR(20) NOT NULL DEFAULT 'UNKNOWN' CHECK (result IN ('CONNECTED','NOT_CONNECTED','UNKNOWN')),
 started_at TIMESTAMP NOT NULL,
 ended_at TIMESTAMP DEFAULT NULL,
 duration_seconds INT NOT NULL DEFAULT 0 CHECK (duration_seconds >= 0),
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT uq_device_android_call UNIQUE(device_id,android_call_log_id),
 CONSTRAINT fk_call_history_employee FOREIGN KEY(employee_id) REFERENCES employees(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_calls_employee_time ON call_history(employee_id,started_at);
CREATE INDEX IF NOT EXISTS idx_calls_time ON call_history(started_at);
CREATE INDEX IF NOT EXISTS idx_calls_device ON call_history(device_id);
CREATE INDEX IF NOT EXISTS idx_calls_result ON call_history(result);

CREATE TABLE IF NOT EXISTS daily_employee_stats (
 employee_id BIGINT NOT NULL,
 stat_date DATE NOT NULL,
 calls_today INT NOT NULL DEFAULT 0 CHECK (calls_today >= 0),
 successful_calls_today INT NOT NULL DEFAULT 0 CHECK (successful_calls_today >= 0),
 unsuccessful_calls_today INT NOT NULL DEFAULT 0 CHECK (unsuccessful_calls_today >= 0),
 talk_seconds_today INT NOT NULL DEFAULT 0 CHECK (talk_seconds_today >= 0),
 idle_seconds_today INT NOT NULL DEFAULT 0 CHECK (idle_seconds_today >= 0),
 PRIMARY KEY(employee_id,stat_date),
 CONSTRAINT fk_daily_stats_employee FOREIGN KEY(employee_id) REFERENCES employees(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS warning_commands (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 employee_id BIGINT NOT NULL,
 device_id VARCHAR(190) NOT NULL,
 command_type VARCHAR(40) NOT NULL DEFAULT 'IDLE_WARNING',
 message VARCHAR(255) NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 delivered_at TIMESTAMP DEFAULT NULL,
 acknowledged_at TIMESTAMP DEFAULT NULL,
 CONSTRAINT fk_warning_employee FOREIGN KEY(employee_id) REFERENCES employees(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_warning_device ON warning_commands(device_id,delivered_at);
CREATE INDEX IF NOT EXISTS idx_warning_employee ON warning_commands(employee_id,created_at);

CREATE TABLE IF NOT EXISTS audit_logs (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 manager_id BIGINT DEFAULT NULL,
 action VARCHAR(100) NOT NULL,
 details TEXT DEFAULT NULL,
 ip_address VARCHAR(45) DEFAULT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_audit_logs_manager FOREIGN KEY(manager_id) REFERENCES managers(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_audit_time ON audit_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_audit_manager ON audit_logs(manager_id);
