let employees=[];let selectedEmployeeId=null;let employeeModal,qrModal;const $=id=>document.getElementById(id);
async function api(path,opt={}){const r=await fetch(APP_CONFIG.API_BASE_URL.replace(/\/$/,'')+'/'+String(path).replace(/^\//,''),{credentials:'include',headers:{'Content-Type':'application/json'},...opt});const text=await r.text();let x={};try{x=text?JSON.parse(text):{}}catch(_){x={error:text||'Empty server response'}}if(!r.ok)throw Error((x.error||'Request failed')+' [HTTP '+r.status+' '+r.url+']');return x}
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function sec(s){s=+s||0;const h=Math.floor(s/3600),m=Math.floor(s%3600/60),z=s%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(z).padStart(2,'0')}`:`${m}:${String(z).padStart(2,'0')}`}
function statusLabel(s){return ({READY:'Ready',IN_CALL:'In Call',IDLE:'Idle',OFFLINE:'Offline'})[s]||'Offline'}
function render(){const q=$('search').value.toLowerCase(),f=$('filter').value;const a=employees.filter(e=>(!f||e.computed_status===f)&&(`${e.name} ${e.department||''} ${e.device_id||''}`).toLowerCase().includes(q));$('rows').innerHTML=a.map(e=>{const map={READY:['Ready','ready'],IN_CALL:['In Call','call'],IDLE:['Idle','idle'],OFFLINE:['Offline','offline']},m=map[e.computed_status]||map.OFFLINE;return `<tr class="employee-row" onclick="openEmployee(${e.id})"><td><b>${esc(e.name)}</b><br><small class="text-secondary">${esc(e.department||'')}</small></td><td>${esc(e.model||'Android')}<br><small class="mono">${esc(e.device_id||'')}</small></td><td><span class="dot ${m[1]}"></span>${m[0]}</td><td>${e.calls_today||0}</td><td>${e.successful_calls_today||0}</td><td>${e.unsuccessful_calls_today||0}</td><td>${sec(e.talk_seconds_today)}</td><td>${e.battery_level==null?'—':e.battery_level+'%'}</td><td>${e.last_seen?new Date(e.last_seen.replace(' ','T')+'Z').toLocaleString():'—'}</td><td><button class="btn btn-sm btn-outline-primary" onclick="event.stopPropagation();openEmployee(${e.id})">View</button></td></tr>`}).join('')||'<tr><td colspan="10" class="empty">No employees match the filter.</td></tr>';$('total').textContent=employees.length;$('ready').textContent=employees.filter(e=>e.computed_status==='READY').length;$('incall').textContent=employees.filter(e=>e.computed_status==='IN_CALL').length;$('idle').textContent=employees.filter(e=>e.computed_status==='IDLE').length;$('totalCalls').textContent=employees.reduce((n,e)=>n+(+e.calls_today||0),0);$('totalSuccessful').textContent=employees.reduce((n,e)=>n+(+e.successful_calls_today||0),0)}
async function refresh(){try{const x=await api('/dashboard');employees=Array.isArray(x.employees)?x.employees:[];$('live').className='badge text-bg-success';$('live').textContent='Live';render()}catch(e){if(String(e.message).toLowerCase().includes('unauthorized')){location='login.html';return}$('live').className='badge text-bg-danger';$('live').textContent='API error';console.error(e)}}
async function openEmployee(id){selectedEmployeeId=id;try{const x=await api('/employee/detail?id='+encodeURIComponent(id));const e=x.employee;$('detailName').textContent=e.name;$('detailDept').textContent=e.department||'No department';$('dStatus').textContent=statusLabel(e.computed_status);$('dDevice').textContent=(e.model||'Android')+' • '+(e.device_id||'—');$('dCalls').textContent=e.calls_today||0;$('dTalk').textContent=sec(e.talk_seconds_today);$('dSuccess').textContent=e.successful_calls_today||0;$('dFail').textContent=e.unsuccessful_calls_today||0;$('dBattery').textContent=e.battery_level==null?'—':e.battery_level+'%';$('dSeen').textContent=e.last_seen?new Date(e.last_seen.replace(' ','T')+'Z').toLocaleString():'—';$('detailStatus').className='alert '+(e.computed_status==='IDLE'?'alert-warning':e.computed_status==='IN_CALL'?'alert-primary':e.computed_status==='READY'?'alert-success':'alert-secondary');$('detailStatus').textContent=e.computed_status==='IDLE'?'⚠ Employee is idle.':e.computed_status==='IN_CALL'?'Employee is currently in a call.':'Current status: '+statusLabel(e.computed_status);$('warnBtn').disabled=!e.device_id||e.computed_status==='OFFLINE';$('recentCalls').innerHTML=(e.recent_calls||[]).map(c=>`<tr><td>${esc(c.started_at||'—')}</td><td class="mono">${esc(c.contact_number||'Unknown')}</td><td><span class="badge ${c.result==='CONNECTED'?'text-bg-success':c.result==='NOT_CONNECTED'?'text-bg-danger':'text-bg-secondary'}">${esc(c.result)}</span></td><td>${sec(c.duration_seconds)}</td><td>${esc(c.direction)}</td></tr>`).join('')||'<tr><td colspan="5" class="text-secondary">No call history recorded.</td></tr>';employeeModal.show()}catch(e){alert(e.message)}}
async function warnSelected(){if(!selectedEmployeeId)return;$('warnBtn').disabled=true;try{await api('/employee/warn',{method:'POST',body:JSON.stringify({employee_id:selectedEmployeeId})});$('warnBtn').textContent='✓ Warning queued';setTimeout(()=>{$('warnBtn').textContent='⚠ Send warning';$('warnBtn').disabled=false},1800)}catch(e){alert(e.message);$('warnBtn').disabled=false}}
async function generateQR(){try{const x=await api('/join/token',{method:'POST',body:'{}'});$('joinToken').value=x.token;$('expiry').textContent='Expires '+new Date(x.expires_at).toLocaleString();const data=encodeURIComponent(x.token);const img=$('qrImage');img.onerror=()=>{img.src='https://quickchart.io/qr?size=520&margin=4&ecLevel=H&text='+data};img.src='https://api.qrserver.com/v1/create-qr-code/?size=520x520&margin=18&ecc=H&data='+data;qrModal.show()}catch(e){alert(e.message)}}
async function copyJoinToken(){const v=$('joinToken').value;if(!v)return;try{await navigator.clipboard.writeText(v)}catch(_){$('joinToken').select();document.execCommand('copy')}}
async function logout(){await api('/auth/logout',{method:'POST'});location='login.html'}
document.addEventListener('DOMContentLoaded',()=>{employeeModal=new bootstrap.Modal($('employeeModal'));qrModal=new bootstrap.Modal($('qrModal'));refresh();setInterval(refresh,5000)});
